### ISSUE TITLE
Notebook idea: interacting with ChEMBL

### ISSUE THREAD

**Issue by cthoyt** [PatWalters/practical_cheminformatics_tutorials#1]
I think a lot of people build their own datasets by ad-hoc working with ChEMBL - you probably remember my excitement to get people to more reproducibly download, access, and cache subsets of it using `chembl_downloader`. Maybe would be a nice tutorial as well.

**Comment by PatWalters** [comment]
Yes, definitely!  I need to check whether chembl_downloader will work on Colab.  I've found that some websites (e.g. Zinc) don't accept connections from Colab.
