### ISSUE TITLE
sparse renamed to sparse_output in sklearn 1.2

### ISSUE THREAD

**Issue by baoilleach** [PatWalters/practical_cheminformatics_tutorials#10]
FYI, regarding the Free Wilson notebook, I had to make a minor change:

![image](https://github.com/PatWalters/practical_cheminformatics_tutorials/assets/45337/c13dc53d-1cc0-44b5-8622-8a2600241896)

**Comment by PatWalters** [comment]
Fixed, thanks Noel!
