### ISSUE TITLE
Notebook on Stereoisomer and Tautomer generation

### ISSUE THREAD

**Issue by PatWalters** [PatWalters/practical_cheminformatics_tutorials#11]
### Discussed in https://github.com/PatWalters/practical_cheminformatics_tutorials/discussions/9

<div type='discussions-op-text'>

<sup>Originally posted by **sitanshubhunia** October 26, 2023</sup>
Thanks for your helpful resources @PatWalters . It's helped me a lot to learn. Requesting you to make a useful notebook on how to generate  **Stereoisomer** and **Tautomer** . That would be very helpful to me. </div>

**Comment by sitanshubhunia** [comment]
@PatWalters Thanks for your time and kind attention. Eagerly waiting for the Notebook.

**Comment by PatWalters** [comment]
Added a new tutorial. 
https://colab.research.google.com/github/PatWalters/practical_cheminformatics_tutorials/blob/main/fundamentals/stereo_and_tautomers.ipynb
