### ISSUE TITLE
Classification model notebook - suggested code updates

### ISSUE THREAD

**Issue by jhylin** [PatWalters/practical_cheminformatics_tutorials#12]
Hi Pat,

Thanks for providing these cheminformatics tutorials and blog posts, I've been learning a lot from them. I was going through the classification notebook (classification_model.ipynb) and had to change the plot code when running it in Google Colab. These code involved the ROC curve, confusion matrix (due to deprecations of old code for sklearn version 1.2 onwards e.g. [ROC curve](https://scikit-learn.org/stable/auto_examples/release_highlights/plot_release_highlights_0_22_0.html#new-plotting-api)) and dtreeviz plot (seemed to have code updates as shown from [dtreeviz repository](https://github.com/parrt/dtreeviz)). 

I also happened to come across an issue with one of the SMILES that could not be processed during the "standardize" process (I've added a quick fix in the notebook link as provide below, but unsure if this was appropriate, please check if possible). I've also added some smaller changes to package import code to tie in with the changed plot code too. All code updates were added to [another version of this notebook](https://github.com/jhylin/practical_cheminformatics_tutorials/blob/main/ml_models/classification_model_v1.ipynb) in my forked repo to avoid taking up too much space here. 

Thanks again,
Jennifer

**Comment by PatWalters** [comment]
Hi Jennifer,

Thank you so much for all the fixes.  I really appreciate the time you put into this!  I made a couple of minor tweaks to your version and updated the repo.  

Thanks again,

Pat
