### ISSUE TITLE
KMeans clusters with minimum silhouette score. Why?

### ISSUE THREAD

**Issue by ismorphism** [PatWalters/practical_cheminformatics_tutorials#6]
Dear Patrick Walters,

Thank you a lot for your work and tutorials you are making - they help to start work in cheminformatics or to look at a chemistry project from different perspective.

But when I was going through the notebook `kmeans_clustering.ipynb` I've found that you used amount of Kmeans clusters as 13 with minimum silhouette score. Shouldn't it be with highest one? The higher the score the better I suppose. Also, the phrase `One means of determining the optimal number of clusters is by minimizing the silhouette score.` (https://colab.research.google.com/github/PatWalters/practical_cheminformatics_tutorials/blob/main/clustering/kmeans_clustering.ipynb#scrollTo=8fb9157a) should be different then. We are trying to maximize the `silhouette score` for choosing the optimal amount of clusters if I get the `silhouette score` idea right.

Thanks in advance.

**Comment by PatWalters** [comment]
Thanks for pointing this out.  You are correct, the silhouette score is between -1 and 1, with values closer to 1 indicating more homogeneous clusters.  I've updated the notebook and the accompanying descriptions.

**Comment by ismorphism** [comment]
@PatWalters Thanks a lot!
