### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by arogozhnikov** [PatWalters/practical_cheminformatics_tutorials#8]
Chembl notebook:

`molecular weight is between 200 and 200` should be `molecular weight is between 200 and 1000` 

Sklearn notebook:

`pip install sklearn -> pip install scikit-learn` (old synonym was deprecated for reasons)

Thanks for tutorials!

**Comment by PatWalters** [comment]
Thank you!  I can't believe I missed this report.
